# Generated by Django 4.0.6 on 2022-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_washing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='washing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='washing',
            name='date',
            field=models.DateField(verbose_name='Washing/Detail Date'),
        ),
    ]
