# Generated by Django 4.0.6 on 2022-07-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_helmet_alter_washing_options_alter_washing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='helmets',
            field=models.ManyToManyField(to='main_app.helmet'),
        ),
    ]
